import './Table.css'

function Table(){
  return(
    <div>
      <table>
        <caption> Build your new habits!</caption>
        <colgroup>
          <col className='todoName'/>
        
        </colgroup>
      <thead>
        <tr>
          <th>{'Habit / Date'}</th>
          <th>{1}</th>
          <th>{2}</th>
          <th>{3}</th>
          <th>{4}</th>
          <th>{5}</th>
          <th>{6}</th>
          <th>{7}</th>
          <th>{8}</th>
          <th>{9}</th>
          <th>{10}</th>
          <th>{11}</th>
          <th>{12}</th>
          <th>{13}</th>
          <th>{14}</th>
          <th>{15}</th>
          <th>{16}</th>
          <th>{17}</th>
          <th>{18}</th>
          <th>{19}</th>
          <th>{20}</th>
          <th>{21}</th> 
          <th>{22}</th> 
          <th>{23}</th> 
          <th>{24}</th> 
          <th>{25}</th> 
          <th>{26}</th> 
          <th>{27}</th> 
          <th>{28}</th> 
          <th>{29}</th> 
          <th>{30}</th> 
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{''}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
        </tr>
        <tr>
        <td>{''}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
          <td>{2}</td>
        </tr>
      </tbody>
    </table>
  </div>
  )
}

export default Table